### ISSUE TITLE
Kashida does not work with some fonts!

### ISSUE THREAD

**Issue by javadr** [xepersian/xepersian#1]
## Check/indicate
- [ ] Relevant to the `bidi` package
- [ ] [The `bidi` package issue tracker](https://github.com/xepersian/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/xepersian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}

\usepackage[Kashida]{xepersian}
\settextfont{Yas}%IRXLotus}

\begin{document}
تست کشیدگی متن

زی‌پرشین \xepersiandate \xepersianversion

بایدی \bididate \bidiversion

\end{document}
```
In the latest update of `bidi/xepersian`, the `Kashida` option fails to function correctly with certain fonts, such as `Yas` and the `XB Series`. However, it performs flawlessly with the `IRLotus` font.
 
![image](https://github.com/user-attachments/assets/ba9ed834-54d9-455c-aef0-d6af2b40fbc2)

## Expected behavior
![image](https://github.com/user-attachments/assets/1d35c00d-1edb-4c94-914c-68615a980e9a)

## Log and PDF files 
[test.log](https://github.com/user-attachments/files/18138013/test.log)
[test.pdf](https://github.com/user-attachments/files/18138014/test.pdf)

**Comment by vkhalighi** [comment]
Thanks for your bug report. The latest versions of the `bidi` and `xepersian` packages are not the cause of this bug. This bug has existed for more than two years and has already been reported [here](https://github.com/tex-persian/xepersian/issues/12). It is due to how XeTeX / Harfbuzz changed its behavior. I need to adapt Kashida to this new behavior.

**Comment by javadr** [comment]
Dear Vafa,

Thank you for your prompt response; I wasn't aware of that! I typically use this feature when I want to typeset traditional poetry. It is great news that you have decided to adopt the code with the new Harfbuzz.

**Comment by vkhalighi** [comment]
I have uploaded version `25.4` of the `xepersian` package to CTAN which should fix this issue.

The cause of the issue was applying left to right mark (`U+200E`) and I removed it to fix the issue. Applying `U+200E` was a nonstandard approach and only was specific to XB Series fonts and various other derived fonts. This worked few years ago but now the behavior of XeTeX / Harfbuzz has changed and this ugly hack no longer works. We should indeed avoid using such nonstandard approaches.

However, this reintroduces an old issue with XB Series font with applying `U+200D` after `U+0647`:

\font\testfont="[Yas.ttf]:script=arab" at 100pt
\testfont
\char"0647\char"200D\char"0631
\bye

<img width="307" alt="Screenshot 2024-12-17 at 3 35 42 PM" src="https://github.com/user-attachments/assets/7f25cc78-0321-42d0-a202-db224016ee49" />


This is a XB Series font issue really and it should be fixed in the font itself. It does not exist in other fonts.

**Comment by vkhalighi** [comment]
I believe that I found the bug in XB Series fonts and its various other derived fonts with regard to applying `U+200D` after `U+0647`. This issue is also inherited by any other fonts based on XB Series fonts. This is a font bug and should be reported to the effected font authors to be fixed. The exact issue is that

> U0647 + U200D gets replaced by the glyph index 559 while it should be replaced by the glyph index 561

Note that the fix is extremely easy. One has to edit the font opentype tables. Since it is a font bug, I do not consider it a `xepersian` package issue.

```tex
\font\testfont="[Yas.ttf]:script=arab" at 100pt
\testfont
\char"0647\char"200D\char"0631

\XeTeXglyph559 % U0647 + U200D gets replaced by the glyph index 559 while it should be replaced by the glyph index 561

\XeTeXglyph561

\TeXXeTstate=1
\beginR\XeTeXglyph561\char"200D\char"0631\endR


\bye
```
<img width="327" alt="Screenshot 2024-12-17 at 5 12 11 PM" src="https://github.com/user-attachments/assets/928c20c4-fb72-41aa-b30b-9a1e255962bd" />

**Comment by vkhalighi** [comment]
Note that the glyph indexes 559 and 561 are specific to XB Yas font. Other fonts probably have different glyph indexes for the same glyph.

**Comment by javadr** [comment]
Thank you so much, as always, for the quick and efficient fix!
